# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7924593d2b0332a5e31262cf77c558d1c2fb25214eab716fa4c4cebef0383c61227fe2003fbee1e52b133b92d8006c3a8fd56a76cf41677388c90c3cb44151f

test:
  secret_key_base: 409efe27c0770f48ce6e5e9fc8a8fa7423ecab92d1b5668962c7df7b41db53c52b63835ee292abf02e1495d3250cb83b1670c1abbfa4f6b83a312327f1e3b7b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
